### PR TITLE
Add Julia v0.7 support

### PR DESCRIPTION
**Pull request by jw3126**

### CODE REVIEW

**Comment by jw3126** [comment]
@ahojukka5  @TeroFrondelius I would like to merge this and #14 and then tag a release. What do you think?

**Comment by TeroFrondelius** [comment]
Definitely just merge and tag. Attobot is really useful but needs to be enabled before taging. Sorry that I haven't contributed, my days just seem to vanish somewhere.

**Comment by jw3126** [comment]
I tried to enable attobot, but I lack permission. Can you please do it?

**Comment by TeroFrondelius** [comment]
> Okay, attobot was updated for the @JuliaFEM account.

Now it should be on for every repo in JuliaFEM.

**Pull request merged**
