### PR TITLE
Windows testing by appveyor

### PR DESCRIPTION
**Pull request by TeroFrondelius**

### CODE REVIEW

**Comment by TeroFrondelius** [comment]
@jw3126 can you check the weird Windows 32 bits test results: https://ci.appveyor.com/project/JuliaFEM/boundingsphere-jl/builds/19853892/job/22i5076itn2g2g10

**Comment by jw3126** [comment]
Looks indeed weird. Does it persist, if you rerun?

**Comment by TeroFrondelius** [comment]
Rerun

**Comment by TeroFrondelius** [comment]
@jw3126 looks consistent both x86 builds fails on AppVeyor. I see two options: 1. Fix the tests or 2. drop the x86 testing. Which option you prefer?

**Comment by jw3126** [comment]
I will investigate it a bit. If I don't find the problem or it turns out hard to fix, I would just drop windows 32bit. I will tell you once I am done.

**Comment by jw3126** [comment]
@TeroFrondelius okay I think just drop 32bit for now. I don't know what the problem is precisely. I just found out
* All other tests work fine on 32 bit
* Its painful to debug, IMO not worth the trouble

**Pull request merged**
